import pyaudio

AUDIO_FRAMES_PER_BUFFER = 1024
AUDIO_FORMAT = pyaudio.paInt16
AUDIO_CHANNELS = 1
AUDIO_RATE = 16000
AUDIO_THRESHOLD = 500

AUDIO_CHUNK_SIZE=50

WHISPER_MODEL_SIZE="medium.en"

# CPU
WHISPER_DEVICE_TYPE="cpu"
WHISPER_COMPUTE_TYPE="int8"
WHISPER_BEAM_SIZE=5

# CUDA (mode) 
# WHISPER_DEVICE_TYPE="cuda"
# WHISPER_COMPUTE_TYPE="int8_float16"